server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://39.105.17.34:8306/mybbs?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234567
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    # 使用druid
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  thymeleaf:
    cache: false

#  resources:
#    static-locations: ["classpath:static/", "file:./static/"]

# 配置mapper.xml位置，这个位置可以在pom.xml里配置
mybatis:
  config-location: classpath:config/mybatis/mybatis-config.xml
  mapperLocations: classpath:/config/mybatis/mapper/bbs/*Mapper.xml
  typeAliasesPackage: com.graduation.bbs.model
#  checkConfigLocation: true
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com:
      graduation:
        bbs:
          dao: debug

